#!/usr/bin/env python3
"""Regenerate core/src/engine/DeviceProfilesData.cpp from presets/devices/device-profiles.json.

The JSON file is the source of truth; tests/test_device_profiles.cpp fails if
the embedded copy drifts. Run from anywhere in the repository:
    python3 tools/scripts/embed-device-profiles.py           # rewrite the .cpp
    python3 tools/scripts/embed-device-profiles.py --check   # exit 1 if it is stale
"""
import argparse
import json
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parents[2]
src = root / "presets" / "devices" / "device-profiles.json"
dst = root / "core" / "src" / "engine" / "DeviceProfilesData.cpp"
DELIM = "FLUBJSON"
MAX_BYTES = 16000  # one MSVC string literal


def generate() -> str:
    text = src.read_text(encoding="utf-8")
    json.loads(text)  # validate before embedding
    if f"){DELIM}\"" in text:
        sys.exit("delimiter collision")
    if len(text.encode("utf-8")) > MAX_BYTES:
        sys.exit("profile file too large for one MSVC string literal; split it")
    return (
        "// GENERATED by tools/scripts/embed-device-profiles.py from\n"
        "// presets/devices/device-profiles.json - do not edit by hand.\n"
        "#include \"flub/engine/DeviceProfiles.h\"\n\n"
        "namespace flub::device\n{\n"
        "const char* builtInProfilesJson() noexcept\n{\n"
        f"    return R\"{DELIM}(" + text + f"){DELIM}\";\n"
        "}\n} // namespace flub::device\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if DeviceProfilesData.cpp does not match the JSON")
    args = parser.parse_args()

    content = generate()
    current = dst.read_text(encoding="utf-8") if dst.exists() else ""
    if args.check:
        if current != content:
            print(f"{dst.relative_to(root)} is stale: run tools/scripts/embed-device-profiles.py", file=sys.stderr)
            return 1
        print(f"{dst.relative_to(root)} is up to date")
        return 0
    if current == content:
        print(f"{dst.relative_to(root)} already up to date")
        return 0
    dst.write_text(content, encoding="utf-8")
    print(f"wrote {dst.relative_to(root)} ({len(src.read_text(encoding='utf-8'))} bytes of JSON)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
