#!/usr/bin/env python3
"""Regenerate core/src/engine/DeviceProfilesData.cpp from presets/devices/device-profiles.json.

The JSON file is the source of truth; tests/test_device_profiles.cpp fails if
the embedded copy drifts. Run from the repository root:
    python3 tools/scripts/embed-device-profiles.py
"""
import json
import pathlib
import sys

root = pathlib.Path(__file__).resolve().parents[2]
src = root / "presets" / "devices" / "device-profiles.json"
dst = root / "core" / "src" / "engine" / "DeviceProfilesData.cpp"

text = src.read_text(encoding="utf-8")
json.loads(text)  # validate before embedding
delim = "FLUBJSON"
if f"){delim}\"" in text:
    sys.exit("delimiter collision")
if len(text.encode("utf-8")) > 16000:
    sys.exit("profile file too large for one MSVC string literal; split it")

dst.write_text(
    "// GENERATED by tools/scripts/embed-device-profiles.py from\n"
    "// presets/devices/device-profiles.json - do not edit by hand.\n"
    "#include \"flub/engine/DeviceProfiles.h\"\n\n"
    "namespace flub::device\n{\n"
    "const char* builtInProfilesJson() noexcept\n{\n"
    f"    return R\"{delim}(" + text + f"){delim}\";\n"
    "}\n} // namespace flub::device\n",
    encoding="utf-8",
)
print(f"wrote {dst.relative_to(root)} ({len(text)} bytes of JSON)")
